language: node_js
sudo: true
node_js:
- node
- '7'
env:
  global:
  - AWS_INSTANCE=ec2-user@ec2-34-210-128-162.us-west-2.compute.amazonaws.com
  - AWS_CERT=$TRAVIS_BUILD_DIR/scripts/key.pem
  - SSH_CMD='ssh -o "StrictHostKeyChecking no" -i $AWS_CERT'
before_install:
- openssl aes-256-cbc -K $encrypted_70e59a8457bc_key -iv $encrypted_70e59a8457bc_iv
  -in secrets.tar.enc -out ./secrets.tar -d
- tar xvf secrets.tar
- source /etc/lsb-release && echo "deb http://download.rethinkdb.com/apt
  $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
- wget -qO- https://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
- sudo apt-get update
- sudo apt-get install rethinkdb
- yarn global add horizon
after_success:
- yarn coverage
- yarn publish-coverage
before_deploy:
  - ssh -o "StrictHostKeyChecking no" -i $AWS_CERT $AWS_INSTANCE
    'bash -xs' < $TRAVIS_BUILD_DIR/scripts/before_deploy.sh
deploy:
  provider: script
  skip_cleanup: true
  script: >
    rsync -e SSH_CMD -r --delete-after --quiet
    $TRAVIS_BUILD_DIR/ $AWS_INSTANCE:/home/ec2-user/ninjathon/
  on:
    branch: master
after_deploy:
  - ssh -o "StrictHostKeyChecking no" -i $AWS_CERT $AWS_INSTANCE
    'bash -xs' < $TRAVIS_BUILD_DIR/scripts/after_deploy.sh
